#Using custom docker image with QT 5.4 configured
image: rabits/qt:5.4-desktop

pipelines:
  default:
    - step:
        script:
          - echo 'C++ Compiler Version'
          - g++ --version
          - echo 'QMake version'
          - qmake --version
          - mkdir build
          - cd build
          - qmake ../InterestPointsDetector.pro
          - make
